"""add_chat_settings_table

Revision ID: 1b1327d83d15
Revises: daabce827dc3
Create Date: 2026-04-13 01:08:30.081231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b1327d83d15'
down_revision: Union[str, Sequence[str], None] = 'daabce827dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('zero_leaks_mode', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('max_row_limit', sa.Integer(), server_default=sa.text('100'), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_index(op.f('ix_connections_user_id'), 'connections', ['user_id'], unique=False)
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index('ix_messages_chat_id_created_at', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_parent_id'), 'messages', ['parent_id'], unique=False)
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_messages_parent_id'), table_name='messages')
    op.drop_index('ix_messages_chat_id_created_at', table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_index(op.f('ix_connections_user_id'), table_name='connections')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_table('chat_settings')
    # ### end Alembic commands ###
